services:
  vault:
    image: hashicorp/vault:1.17.6
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - ./data:/vault/file
    command: vault server -config=/vault/config/config.hcl
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
