FROM python:3.12-slim

# تحديث حزم النظام لإصلاح ثغرات OpenSSL وغيرها
RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# ... باقي خطوات الـ Dockerfile الخاصة بك

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "app.py"]
